adding support for urdu
wojtekmaj/react-lifecycle-methods-diagram pull request #98
Opened 2022-11-03 12:22 UTC by rabbanirizwan

files included containing support Urdu language

2022-11-04 13:40 UTC, wojtekmaj requested changes
Almost there :)

2022-11-04 13:40 UTC, wojtekmaj commented on src/i18n/i18n.js
> +  'ur': () => import(/* webpackChunkName: "uk-UA" */ './json/ur.json'),
```suggestion
  'ur': () => import(/* webpackChunkName: "ur" */ './json/ur.json'),
```

2022-11-04 13:40 UTC, wojtekmaj commented on src/i18n/json/ur.json
> +  "//reactjs.org/docs/react-component.html#{docname}": "//vi.reactjs.org/docs/react-component.html#{docname}",
Sure you want links to Vietnamese docs? :)

```suggestion
  "//reactjs.org/docs/react-component.html#{docname}": "//ur.reactjs.org/docs/react-component.html#{docname}",
```

2022-11-04 13:40 UTC, wojtekmaj commented on src/i18n/languages.json
> +    "name": "اردو",
```suggestion
    "name": "Urdu",
```

2022-11-07 10:14 UTC, rabbanirizwan commented on src/i18n/json/ur.json
> +  "//reactjs.org/docs/react-component.html#{docname}": "//vi.reactjs.org/docs/react-component.html#{docname}",
I have changed it to eng because at the moment react does not support Urdu

2022-11-07 10:14 UTC, rabbanirizwan commented on src/i18n/i18n.js
> +  'ur': () => import(/* webpackChunkName: "uk-UA" */ './json/ur.json'),
resolve

2022-11-07 10:14 UTC, rabbanirizwan commented on src/i18n/languages.json
> +    "name": "اردو",
resolve

2022-11-07 11:47 UTC, wojtekmaj commented on src/i18n/json/ur.json
> +  "//reactjs.org/docs/react-component.html#{docname}": "//vi.reactjs.org/docs/react-component.html#{docname}",
Hmmm, locale is there, live: https://ur.reactjs.org/

2022-11-08 12:03 UTC, wojtekmaj approved these changes

2022-11-08 12:04 UTC, merged